name: petsica
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  animated_text_kit: ^4.2.3
  another_flushbar: ^1.12.30
  device_preview: ^1.2.0
  draggable_fab: ^0.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_plugin_android_lifecycle: 2.0.17
  flutter_profile_picture: ^2.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_mlkit_face_detection: ^0.12.0
  http: ^1.3.0
  image_picker: ^1.1.0
  redacted: ^1.0.13
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.6
  shimmer: ^3.0.0
  typewritertext: ^3.0.9

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
