import 'package:flutter/material.dart';

const kAppColor = Color(0xffEAE6E3);
const kWhiteGroundColor = Color(0xfffcfcfc);
const kLightContainerColor = Color(0xfff9f9f9);
const kLightAddContainerColor = Color(0xffe2e4e1);
const kChatBackGroundColor = Color(0xfff8f8f8);
const kWordColor = Colors.black;
const kContainerColor = Colors.white;
const kTextFieldColor = Color(0xffFAF7F6);
const kStorkTextFieldColor = Color(0xff987478);
const kBurgColor = Color(0xff70161E);
const kAddColor = Color(0xff31362f);
const kInputWordColor = Color(0xff7D7C7B);
const kAccountColor = Color(0xff4B4A4A);
const kIconsColor = Color(0xff757575);
const kProductTxtColor = Color(0xff07060B);
const kLightProductTxtColor = Color(0xffaeb5ab);
const kProducPriceColor = Color(0xff788373);
const kStoreContainerColor = Color(0xfff9f7fa);
const kRemoveColor = Color(0xffe22c3c);
const kInputFieldBackgroundColor = Color(0xfff5f5f5);
const kAddPetContainerColor = Color(0xffe8ebe6);
const kAddPetTextColor = Color(0xff5d5e5c);
